#!/bin/bash -e

if [[ -n "$1" ]]; then
    echo usage: aoc input >&2
    exit 1
fi

script_dir=$(dirname $BASH_SOURCE)
cookie=$script_dir/../user-session
day_pattern='day-'

if [[ ! "$(basename $PWD)" =~ "^${day_pattern}[0-9][0-9]$" ]]; then
    echo "Error: you need to be in a '${day_pattern}DD/' directory" >&2
    exit 1
fi

day=$(basename $PWD | sed "s/^$day_pattern//")

if [[ ! -f $cookie ]]; then
    echo "Error: you need to copy your session in 'aoc/user-session'" >&2
    exit 1
fi

curl -s https://adventofcode.com/2022/day/$day/input --cookie "session=$(< $cookie)" > input
